### ISSUE TITLE
Development framework for the soundboard

### ISSUE THREAD

**Issue by SpadesNeil** [MTS11648/Don-NonAutomated-Bot#1]
#### Brief description of the issue:
Just listing things that will need to be included for the soundboard to be functional to a point where we can easily update it.

- [x] Common responses/rebuttals will be accessible via button clicking, and/or a list of shortcuts which will be on screen at all times. Examples: "Yes" "No" "Okay" "Just a moment while I put this in" "Haha" "Thank you" "LCN stands for loud cloud nine" "We got your info from blah blah blah" etc.
- [x] There should be a dynamic auto questions div that will change on the screen depending on which question is currently active. Each question will have its own list of answers that correspond to different audio files. All should be accessible either by clicking on them, or pressing the number keys 0 through 9.
- [x] To repeat the current question, users should be able to both click on the question, and to be able to press a shortcut (such as the enter key, perhaps).
- [ ] ~~To navigate to previous questions, there should be a back button, as well as a menu for jumping to other questions.~~ Won't add
- [x] Hang up responses should also be visible at all times too, but should not be possible to press with shortcuts.
- [x] There should be an option to stop all sound at any time, just in case the user hits the wrong button.

Everything we add should be easily expansible for future additions and updates. If @MTS11648 can produce the framework in a way that can be expanded easily, I can handle adding the questions.

#### Additional info:
 - **Bot Revision**: Pre-Release

**Comment by MTS11648** [comment]
Everything here is done besides the previous question navigation feature, I think it would be more trouble than what it's worth.

**Comment by SpadesNeil** [comment]
Bumping down to Minor, then.
