### ISSUE TITLE
"INSURANCE COMPANIES" audio is inconsistent.

### ISSUE THREAD

**Issue by MTS11648** [MTS11648/Don-NonAutomated-Bot#33]
#### Brief description of the issue:
Some clips have the "How long have you been with them?" at the end, others don't.
#### What _should_ have happened?:
The clips should _all_ have the "How long have you been with them?" at the end.
#### Steps to reproduce:
1) Get to insurance company question.
2) Press "USAA".
3) Watch how Don kind of just sits there and doesn't ask a follow-up question.

**Comment by MTS11648** [comment]
Tylre is on this right now (I think) so hopefully we can get this resolved quickly.

**Comment by SpadesNeil** [comment]
This is resolved?
