### ISSUE TITLE
Audio clips should not be able to interrupt each other.

### ISSUE THREAD

**Issue by SpadesNeil** [MTS11648/Don-NonAutomated-Bot#35]
#### Brief description of the issue:
https://github.com/MTS11648/Don-NonAutomated-Bot/pull/34 cannot be merged because it is currently skipping the intro clip to immediately play the next clip. This is obviously not correct.

#### What happened?:
During the intro, bot will skip to "Are you currently living in (state)?"

#### What _should_ have happened?:
"Hi, this is Don from LCN (...) and are you currently living in (state)?"

#### Steps to reproduce:
- Play intro.
- ???
- Die a little inside.

#### Additional info:
 - **Bot Revision**: Pre-Release

**Comment by MTS11648** [comment]
Definitely looks like we're going to have to use those _async_ methods.
